# IPC socket created dynamically by scripts/auto-socket.lua
# Socket path: /tmp/mpv-{media-title}-{pid}.sock

cache=yes
cache-secs=300

demuxer-max-bytes=512MiB
demuxer-max-back-bytes=512MiB
demuxer-readahead-secs=300

hwdec=auto

gapless-audio=yes

prefetch-playlist=yes

slang=en,eng,enUS,en-US
sub-auto=fuzzy
stream-buffer-size=20M

vo=gpu

ytdl-raw-options=format-sort="res:1080,vcodec:vp9,acodec:opus,fps",sub-lang="en,eng,enUS,en-US",write-sub=,write-auto-sub=,cookies-from-browser=firefox
ytdl-format=bestvideo[height<=?1920][fps<=?30][vcodec^=avc]+bestaudio/best
